# https://code.visualstudio.com/docs/remote/create-dev-container#_extend-your-docker-compose-file-for-development
version: '3'

services:
  web:
    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - .:/workspace:cached